runtime: python39
entrypoint: gunicorn --bind :$PORT -w 4 wsgi:app
service: default
instance_class: F2

handlers:
  - url: /
    script: wsgi.py
  - url: /.*
    script: wsgi.py

env_variables:
  HOST: 0.0.0.0
